### ISSUE TITLE
Back to the future

### ISSUE THREAD

**Issue by rolandas-simkus** [rolandas-simkus/github-collaboration#1]
We need to create a time machine that would be able to travel to the past and to the future. In order to create this time machine we need to organize a workflow on how to do it.

- [ ] Create engine for time travel machine
  - [ ] Add ability to travel to the past
    - [ ] Make sure that we couldn't change future by altering past
  - [ ] Add ability for travel to the future

![giphy](https://user-images.githubusercontent.com/33152820/54103808-e5b58980-4421-11e9-8e33-e35cf973ffd5.gif)
